'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createTerminalPaste } = require('../renderer/terminal_paste');
const { registerClipboardIpc } = require('../main/clipboard_ipc_bridge');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');

function fixture(readClipboard = async () => 'hello') {
  const calls = [], errors = [];
  let current = true, controller;
  const term = { paste(text) { assert.equal(controller.captureData(text), true); } };
  controller = createTerminalPaste({ term, readClipboard, pastePty: async data => calls.push(data), isCurrent: () => current,
    onError: (...args) => errors.push(args) });
  return { controller, calls, errors, replace: () => { current = false; } };
}
function event(extra = {}) {
  return { type: 'keydown', key: 'v', metaKey: true, ctrlKey: false, prevented: 0, stopped: 0,
    preventDefault() { this.prevented++; }, stopPropagation() { this.stopped++; }, stopImmediatePropagation() { this.stopped++; }, ...extra };
}
const flush = () => new Promise(resolve => setImmediate(resolve));

for (const combo of [{}, { key: 'V' }, { metaKey: false, ctrlKey: true, mac: false }, { metaKey: false, ctrlKey: true, shiftKey: true, mac: false }]) {
  test(`paste shortcut is suppressed synchronously and delivers once: ${JSON.stringify(combo)}`, async () => {
    const f = fixture(), e = event(combo);
    assert.equal(f.controller.key(e, combo.mac !== false), false);
    assert.equal(e.prevented, 1); assert.equal(e.stopped, 1); assert.deepEqual(f.calls, []);
    await flush(); assert.deepEqual(f.calls, ['hello']);
    assert.equal(f.controller.captureData('ordinary typing'), false);
  });
}
test('native menu paste uses the same asynchronous path once', async () => {
  const f = fixture(), e = event({ type: 'paste' });
  f.controller.nativePaste(e); await flush();
  assert.equal(e.prevented, 1); assert.equal(e.stopped, 1); assert.deepEqual(f.calls, ['hello']);
});
test('ordinary keys and macOS Ctrl+V retain terminal behavior', () => {
  const f = fixture();
  for (const e of [event({ type: 'keyup' }), event({ key: 'c' }), event({ metaKey: false, ctrlKey: true })]) {
    assert.equal(f.controller.key(e, true), true); assert.equal(e.prevented, 0);
  }
});
test('delayed clipboard cannot paste after slot replacement', async () => {
  let resolve; const f = fixture(() => new Promise(r => { resolve = r; }));
  const pending = f.controller.paste(); await flush(); f.replace(); resolve('stale'); await pending;
  assert.deepEqual(f.calls, []);
});
test('empty, rejected and stale clipboard reads produce no terminal bytes', async () => {
  for (const read of [async () => '', async () => { throw Error('clipboard unavailable'); }]) {
    const f = fixture(read); await f.controller.paste(); assert.deepEqual(f.calls, []);
  }
  let reads = 0; const f = fixture(async () => { reads++; return 'stale'; }); f.replace();
  await f.controller.paste(); assert.equal(reads, 0);
});
test('paste order waits for delivery and preserves xterm-generated bytes', async () => {
  let controller, release; const calls = [], reads = [];
  controller = createTerminalPaste({
    term: { paste(text) { controller.captureData('\x1b[200~'); controller.captureData(text.replace(/\r?\n/g, '\r')); controller.captureData('\x1b[201~'); } },
    readClipboard: async () => { reads.push(1); return 'a\nb'; }, isCurrent: () => true,
    pastePty: data => { calls.push(data); return calls.length === 1 ? new Promise(r => { release = r; }) : Promise.resolve(); },
  });
  const first = controller.paste(), second = controller.paste(); await flush(); assert.equal(reads.length, 1);
  release(); await Promise.all([first, second]);
  assert.deepEqual(calls, ['\x1b[200~a\rb\x1b[201~', '\x1b[200~a\rb\x1b[201~']);
});
test('clipboard preload bridges asynchronous main API without renderer clipboard export', async () => {
  const handlers = new Map(), writes = [];
  registerClipboardIpc({ handle: (n, f) => handlers.set(n, f) }, {
    readText: async () => 'clipboard text', writeText: async text => { writes.push(text); },
  });
  const context = { window: {}, process, require(name) {
    if (name === 'electron') return { ipcRenderer: { invoke: (name, ...args) => handlers.get(name)({}, ...args), on() {}, send() {}, removeAllListeners() {} } };
    if (name === './config-loader') return { loadConfig: () => ({ config: {} }) };
    return require(name);
  } };
  vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8'), context);
  assert.equal(await context.window.cc.readClipboard(), 'clipboard text');
  await context.window.cc.writeClipboard(42); assert.deepEqual(writes, ['42']);
});
